# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
image: gradle:7.5.1-jdk17

stages:
  - build
  - package
  - createInstaller

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - .m2/repository

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  tags:
    - docker
  only:
    refs:
      - master
      - /^release\/.*$/
      - tags
  script:
    - gradle --build-cache clean assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle
      - application-gui/build
      - application/build
      - common/build
      - nitrite-data/annotation/build
      - nitrite-data/processor/build

package:
  stage: package
  dependencies:
    - build
  tags:
    - docker
  only:
    refs:
      - /^release\/.*$/
      - tags
  script:
    - gradle --build-cache installAppDist
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - application-gui/build/install
    expire_in: 1 days


createInstaller:
  image: docker:latest
  services:
    - docker:dind
  stage: createInstaller
  dependencies:
    - package
  tags:
    - docker
  only:
    refs:
      - /^release\/.*$/
      - tags
  script:
    - cd ./application-gui
    - docker-compose -f ./setup/docker-compose-setup.yml up build-app
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - application-gui/setup/Output