# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - build

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  stage: build
  tags:
    - quieter
  only:
    refs:
      - /^release\/.*$/
      - tags
  script:
    - ./gradlew.bat --build-cache clean assemble createInstaller
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - application-gui/build/installer


