# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
stages:
  - build
  - package

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  image: eclipse-temurin:17.0.7_7-jdk
  stage: build
  tags:
    - docker
  only:
    refs:
      - /^release\/.*$/
      - tags
  script:
    - chmod +x ./gradlew
    - ./gradlew --build-cache clean assemble installAppDist
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - application-gui/build/install
    expire_in: 1 days


createInstaller:
  image: docker:latest
  services:
    - docker:dind
  stage: package
  dependencies:
    - build
  tags:
    - docker
  only:
    refs:
      - /^release\/.*$/
      - tags
  script:
    - chmod +x ./gradlew
    # - ./gradlew --build-cache createInstaller
    - cd ./application-gui
    - docker-compose -f ./setup/docker-compose-setup.yml up build-app
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .gradle
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - application-gui/build/installer